name: Run Tests

on:
on:
  push:
    branches:
      - develop
      - main
      - feature/task_list  # Додано твою гілку
  pull_request:
    branches:
      - develop
      - main
      - feature/task_list  # Додано твою гілку


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Зміни на свою версію Python, якщо потрібно

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest
