name: Run Tests

on:
  push:
    branches:
      - feature/task_list  
  pull_request:
    branches:
      - feature/task_list 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa

      - name: Run Tests
        run: |
          pytest tests/

